FROM nginx:latest

COPY default.conf /etc/nginx/conf.d/default.conf
COPY index.html /usr/share/nginx/html/

# Se for usar SSL, copie os certificados para /etc/nginx/ssl/
# COPY ssl/asa.br.crt /etc/nginx/ssl/asa.br.crt
# COPY ssl/asa.br.key /etc/nginx/ssl/asa.br.key
